### ISSUE TITLE
Parsing error with function call and bit size

### ISSUE THREAD

**Issue by kalidasya** [SonarCommunity/sonar-erlang#10]
The following code snippet is failing:
```
-module(bin_to_hex).
-define(H(X), (hex(X)):16).
hex(X) -> X.
```

```
Parse error at line 3 column 26:
1: -module(bin_to_hex).
2: 
3: -define(H(X), (hex(X)):16).
                            ^
4: 
5: hex(X) -> X.
6: 
```

**Comment by kalidasya** [comment]
the macro is called from a bitstring so its valid, calling from anywhere else of course will be an error... maybe we need a pre-processor?

**Comment by kalidasya** [comment]
@jlrigau what do you think if we ignore the content of the macro definition, till we do not have pre-processor what resolves the macros in the source

**Comment by jlrigau** [comment]
@kalidasya the use of a pre-processor for macros is definitely a good option.

Thanks for the fix on the grammar :)
